---
- debug:
    var: jdk_install_root

- name: "Setup core IITD migration framework, compile schema and generate baseline"
  shell: "chdir={{lb_working_dir}} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=setup,compile_schema migrate -Dstage=pre{{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"

- name: "Clear baseline for stage pre{{cd_version}}"
  shell: "chdir={{lb_working_dir}} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=cleaer_baseline migrate -Dstage=pre{{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"
  when: lb_overwrite_baseline|bool == True

- name: "Generate baseline for stage pre{{cd_version}}"
  shell: "chdir={{lb_working_dir}} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=generate_baseline migrate -Dstage=pre{{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"

- name: "Tag database before running migration"
  shell: "chdir={{lb_working_dir}} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=pre_tag  migrate -Dmigration_tag={{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"
