---
- name: "Setup core IITD migration framework"
  import_tasks: "setup_core.yml"

- name: "Perform application migration for version {{ cd_version }}"
  shell: "chdir={{ lb_working_dir }} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase update -Dapp_version={{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"

- name: "Tag database for version {{ cd_version }}"
  shell: "chdir={{ lb_working_dir }} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase tag {{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"

- name: "Recompile schema"
  shell: "chdir={{ lb_working_dir }} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=compile_schema update"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"

- name: "Clear schema state for stage post{{cd_version}}"
  shell: "chdir={{lb_working_dir}} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=clear_schema_state update -Dstage=post{{cd_version}}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"
  when: lb_overwrite_schema_state|bool == True

- name: "Log schema state for stage post{{cd_version}}"
  shell: "chdir={{ lb_working_dir }} JAVA_HOME={{ cd_app_home }}/jdk {{ lb_liquibase_staging_dir }}/liquibase --changeLogFile=../nrdk/nrdk.xml --contexts=log_schema_state update -Dstage=post{{ cd_version }}"
  become: yes
  become_user: "{{ lb_deploy_scripts_user }}"