---
- name: Check for fluent-bit service
  stat:
    path: /apps_ux/s6_services/fluent-bit/run
  register: fluent_bit_run
  become: yes
  become_user: wwwadm
  tags:
  - uninstall-safe
  - uninstall-all

- name: Stop fluent-bit
  include_role:
    name: tomcat_stop
    apply:
      tags: [uninstall-safe,uninstall-all]
  when: fluent_bit_run.stat.exists
  tags:
  - uninstall-safe
  - uninstall-all

- name: Create apache conf directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ apm_agent_home }}/conf/apache'
    - '{{ apm_agent_home }}/conf/apache/filter'
    - '{{ apm_agent_home }}/conf/apache/input'
    - '{{ apm_agent_home }}/conf/apache/parser'
  become: yes
  become_user: wwwadm

- name: Filter configuration file
  template:
    src: 'templates/{{ item }}'
    dest: '{{ apm_agent_home }}/conf/apache/{{ item }}'
    mode: '0664'
  become: yes
  become_user: wwwadm
  loop:
    - filter/filters.conf

- name: Input configuration file
  copy:
    src: '{{ item }}'
    dest: '{{ apm_agent_home }}/conf/apache'
    mode: '0644'
  become: yes
  become_user: wwwadm
  loop:
    - conf/apache/input

- name: Remove apache config
  file:
    state: absent
    path: '{{ apm_agent_home }}/conf/apache'
  become: yes
  become_user: wwwadm
  tags:
  - never
  - uninstall-safe

- name: Start fluent-bit
  include_role:
    name: tomcat_start
    apply:
      tags: uninstall-safe
  tags:
  - molecule-notest
  - uninstall-safe
