---
- name: "Ensure the target environment has been specified"
  assert:
     that:
        - cdconf_target is defined
        - cd_version is defined

- name: Get secrets from vault
  set_fact:
     vault_secrets: "{{ lookup('community.hashi_vault.hashi_vault', vault_context, token=vault_token, url=vault_url) }}"

- name: "!!Remove!! Show secrets for framework debug"
  debug:
     var: vault_secrets

- name: Get playbook variables file
  get_url:
     url: "{{ playbook_vars_url }}"
     dest: "{{ lookup('env','PWD') }}/playbook_vars.yml"
     url_username: "{{ username }}"
     url_password: "{{ password }}"

- name: Get variables from configuration file
  include_vars: "{{ lookup('env','PWD') }}/playbook_vars.yml"

- name: "Flatten target variables for {{ cdconf_target }}"
  set_fact:
     "{{ item.key }}": "{{ item.value }}"
  with_dict:
     - "{{ lookup('vars', cdconf_target) }}"
     - vault_secrets

- name: "Set variables for liquibase deployment"
  set_fact:
     cd_app_home: "/apps_ux/{{ project }}/{{ artifact_id }}"

- name: Print all available variables
  debug:
    var: vars
