---
- name: "Ensure the target environment has been specified"
  assert:
     that:
        - cdconf_target is defined
        - cd_version is defined

- name: Get playbook variables file
  get_url:
     url: "{{ playbook_vars_url }}"
     dest: "{{ lookup('env','PWD') }}/playbook_vars.yml"
     url_username: "{{ username }}"
     url_password: "{{ password }}"

- name: Get variables from configuration file
  include_vars: "{{ lookup('env','PWD') }}/playbook_vars.yml"

- name: "Flatten target variables for {{ cdconf_target }}"
  set_fact:
     "{{ item.key }}": "{{item.value}}"
  with_dict:
     - "{{ lookup('vars', cdconf_target) }}"

# Tried to do this with the hashi_vault plugin, but without success
- name: Get secrets from vault
  set_fact:
    vault_secrets: "{{ lookup('url', 'https://vault-iit.apps.silver.devops.gov.bc.ca/v1/apps/data/'+cdconf_target+'/'+(project | lower)+'/'+(artifact_id | lower), headers={'X-Vault-Token':vault_token} ) }}"

- name: "Flatten target variables for vault_secrets"
  set_fact:
     "{{ item.key }}": "{{ item.value }}"
  with_dict:
     - "{{ vault_secrets['data']['data'] }}"

- name: "Set variables for liquibase deployment"
  set_fact:
     cd_app_home: "/apps_ux/{{ project }}/{{ artifact_id }}"