---
- name: "Ensure the target environment has been specified"
  assert:
     that:
        - cdconf_target is defined
        - cd_version is defined

- name: Get playbook variables file
  get_url:
     url: "{{ playbook_vars_url }}"
     dest: "{{ lookup('env','PWD') }}/playbook_vars.yml"
     url_username: "{{ username }}"
     url_password: "{{ password }}"

- name: Get variables from configuration file
  include_vars: "{{ lookup('env','PWD') }}/playbook_vars.yml"

- name: "Set variables for liquibase deployment"
  set_fact:
     cd_app_home: "/apps_ux/{{ project }}/{{ artifact_id }}/"

- name: Print all available variables
  debug:
    var: vars
