---
- name: Check for vault broker token
  assert:
    that:
      - vault_broker_token | default('') | length > 0 
    msg: 'Vault broker token variable must not be empty'
  tags:
  - molecule-notest

- name: Create app directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0775'
  loop:
    - '{{ agent_home }}'
    - '{{ agent_home }}/maven'
    - '{{ agent_home }}/maven/.m2'
  become: yes
  become_user: wwwadm

- name: Deploy config
  import_tasks: deploy-config.yml
