---
- name: Create /sw_ux/bin directory
  file:
    path: '/sw_ux/bin'
    state: directory
    mode: '0755'
  become: yes
  become_user: wwwadm

- name: Download jq
  environment: '{{ proxy_env }}'
  get_url:
    url: 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
    dest: '/sw_ux/bin/jq'
    mode: '755'
    use_proxy: yes
  become: yes
  become_user: wwwadm
  when: not ansible_check_mode